---

- name: Push configs to lab nodes
  connection: httpapi
  hosts: lab
  gather_facts: false

  vars:
    ansible_python_interpreter: /usr/bin/python3
    config_dir: "{{ playbook_dir }}/../configs/"

  tasks:

    - name: "Configs from {{ config_dir }}"
      eos_config:
        src: "{{ config_dir }}{{ inventory_hostname }}.cfg"
        replace: config
        save_when: changed
